using Microsoft.VisualStudio.TestTools.UnitTesting;
using qckdev;

namespace qckdevTest
{

    [TestClass]
    public class ExtensionsTest
    {

        [TestMethod]
        [DataRow("patata", true)]
        [DataRow("Patata", false)]
        public void InTest_String(string value, bool expected)
        {
            Assert.AreEqual(expected,
                value.In("lechuga", "patata", "pepino"));
        }

        [TestMethod]
        [DataRow(true, "patata", true)]
        [DataRow(true, "Patata", true)]
        [DataRow(false, "patata", true)]
        [DataRow(false, "Patata", false)]
        public void InTest_String_CaseSensitive(bool ignorecase, string value, bool expected)
        {
            Assert.AreEqual(expected,
                value.In(ignorecase, "lechuga", "patata", "pepino"));
        }

        [TestMethod]
        [DataRow(0, true)]
        [DataRow(10, true)]
        [DataRow(1000, true)]
        [DataRow(42, false)]
        [DataRow(null, true)]
        public void InTest_Int(int value, bool expected)
        {
            Assert.AreEqual(expected,
                value.In(0, 1, 10, 100, 1000));
        }

        [TestMethod]
        [DataRow(0, true)]
        [DataRow(10, true)]
        [DataRow(1000, true)]
        [DataRow(42, false)]
        [DataRow(null, false)]
        public void InTest_Int_Nullable(int? value, bool expected)
        {
            Assert.AreEqual(expected,
                value.In(0, 1, 10, 100, 1000));
        }

        [TestMethod]
        [DataRow(0, true)]
        [DataRow(10, true)]
        [DataRow(1000, true)]
        [DataRow(42, false)]
        [DataRow(null, true)]
        public void InTest_Int_NullableToNull(int? value, bool expected)
        {
            Assert.AreEqual(expected,
                value.In(0, 1, 10, 100, 1000, null));
        }

        [TestMethod]
        [DataRow(true, "abcd?fg", "abcdefg")]
        [DataRow(true, "ab*f*", "abcdefg")]
        [DataRow(false, "abcd?fg", "abcdefghi")]
        [DataRow(true, "*", "")]
        [DataRow(true, "*", " ")]
        [DataRow(true, "*", "asdfa asdf asdf")]
        [DataRow(true, "*", "*")]
        [DataRow(false, "?", "")]
        [DataRow(true, "?", " ")]
        [DataRow(true, "?", "4")]
        [DataRow(true, "?", "C")]
        [DataRow(false, "?", "CX")]
        [DataRow(false, "[ABCD]", "")]
        [DataRow(true, "[ABCD]", "A")]
        [DataRow(true, "[ABCD]", "B")]
        [DataRow(true, "[ABCD]", "b")]
        [DataRow(false, "[ABCD]", "X")]
        [DataRow(false, "[ABCD]", "AB")]
        [DataRow(true, "[B-D]", "C")]
        [DataRow(true, "[B-D]", "D")]
        [DataRow(false, "[B-D]", "A")]
        [DataRow(false, "[^B-D]", "C")]
        [DataRow(false, "[^B-D]", "D")]
        [DataRow(true, "[^B-D]", "A")]
        [DataRow(true, "*TEST[ABCD]XXX", "lolTESTBXXX")]
        [DataRow(false, "*TEST[ABCD]XXX", "lolTESTZXXX")]
        [DataRow(false, "*TEST[^ABCD]XXX", "lolTESTBXXX")]
        [DataRow(true, "*TEST[^ABCD]XXX", "lolTESTZXXX")]
        [DataRow(true, "*TEST[B-D]XXX", "lolTESTBXXX")]
        [DataRow(true, "*TEST[^B-D]XXX", "lolTESTZXXX")]
        [DataRow(true, "*Stuff.txt", "Stuff.txt")]
        [DataRow(true, "*Stuff.txt", "Stuff.TXT")]
        [DataRow(true, "*Stuff.txt", "MagicStuff.txt")]
        [DataRow(true, "*Stuff.txt", "MagicStuff.TXT")]
        [DataRow(false, "*Stuff.txt", "MagicStuff.txt.IMG")]
        [DataRow(false, "*Stuff.txt", "MagicStuff.TXT.IMG")]
        [DataRow(false, "*Stuff.txt", "Stuff.txt.IMG")]
        [DataRow(false, "*Stuff.txt", "Stuff.TXT.IMG")]
        [DataRow(false, "*Stuff.txt", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff.txt", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "Stuff.txt*", "Stuff.txt")]
        [DataRow(true, "Stuff.txt*", "Stuff.TXT")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.txt")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.TXT")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.txt.IMG")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "Stuff.txt*", "Stuff.txt.IMG")]
        [DataRow(true, "Stuff.txt*", "Stuff.TXT.IMG")]
        [DataRow(false, "Stuff.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "Stuff.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff.txt*", "Stuff.txt")]
        [DataRow(true, "*Stuff.txt*", "Stuff.TXT")]
        [DataRow(true, "*Stuff.txt*", "MagicStuff.txt")]
        [DataRow(true, "*Stuff.txt*", "MagicStuff.TXT")]
        [DataRow(true, "*Stuff.txt*", "MagicStuff.txt.IMG")]
        [DataRow(true, "*Stuff.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "*Stuff.txt*", "Stuff.txt.IMG")]
        [DataRow(true, "*Stuff.txt*", "Stuff.TXT.IMG")]
        [DataRow(false, "*Stuff.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt", "Stuff.txt")]
        [DataRow(true, "*Stuff*.txt", "Stuff.TXT")]
        [DataRow(true, "*Stuff*.txt", "MagicStuff.txt")]
        [DataRow(true, "*Stuff*.txt", "MagicStuff.TXT")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff.txt.IMG")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff.TXT.IMG")]
        [DataRow(false, "*Stuff*.txt", "Stuff.txt.IMG")]
        [DataRow(false, "*Stuff*.txt", "Stuff.TXT.IMG")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt", "MagicStuff001.txt")]
        [DataRow(true, "*Stuff*.txt", "MagicStuff001.TXT")]
        [DataRow(true, "Stuff*.txt*", "Stuff.txt")]
        [DataRow(true, "Stuff*.txt*", "Stuff.TXT")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.txt")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.TXT")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.txt.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "Stuff*.txt*", "Stuff.txt.IMG")]
        [DataRow(true, "Stuff*.txt*", "Stuff.TXT.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.txt")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.TXT")]
        [DataRow(true, "*Stuff*.txt*", "Stuff.txt")]
        [DataRow(true, "*Stuff*.txt*", "Stuff.TXT")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff.txt")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff.TXT")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff.txt.IMG")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt*", "Stuff.txt.IMG")]
        [DataRow(true, "*Stuff*.txt*", "Stuff.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff001.txt")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff001.TXT")]
        [DataRow(true, "?Stuff?.txt?", "1Stuff3.txt4")]
        [DataRow(true, "?Stuff?.txt?", "1Stuff3.TXT4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff.txt4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff.TXT4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff3.txt")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff3.TXT")]
        [DataRow(false, "?Stuff?.txt?", "Stuff3.txt4")]
        [DataRow(false, "?Stuff?.txt?", "Stuff3.TXT4")]
        public void LikeTest(bool expected, string pattern, string text)
        {
            Assert.AreEqual(expected, text.Like(pattern));
        }

        [TestMethod]
        [DataRow(true, "abcd?fg", "abcdefg")]
        [DataRow(true, "ab*f*", "abcdefg")]
        [DataRow(false, "abcd?fg", "abcdefghi")]
        [DataRow(true, "*", "")]
        [DataRow(true, "*", " ")]
        [DataRow(true, "*", "asdfa asdf asdf")]
        [DataRow(true, "*", "*")]
        [DataRow(false, "?", "")]
        [DataRow(true, "?", " ")]
        [DataRow(true, "?", "4")]
        [DataRow(true, "?", "C")]
        [DataRow(false, "?", "CX")]
        [DataRow(false, "[ABCD]", "")]
        [DataRow(true, "[ABCD]", "A")]
        [DataRow(true, "[ABCD]", "B")]
        [DataRow(false, "[ABCD]", "b")]
        [DataRow(false, "[ABCD]", "X")]
        [DataRow(false, "[ABCD]", "AB")]
        [DataRow(true, "[B-D]", "C")]
        [DataRow(true, "[B-D]", "D")]
        [DataRow(false, "[B-D]", "A")]
        [DataRow(false, "[^B-D]", "C")]
        [DataRow(false, "[^B-D]", "D")]
        [DataRow(true, "[^B-D]", "A")]
        [DataRow(true, "*TEST[ABCD]XXX", "lolTESTBXXX")]
        [DataRow(false, "*TEST[ABCD]XXX", "lolTESTZXXX")]
        [DataRow(false, "*TEST[^ABCD]XXX", "lolTESTBXXX")]
        [DataRow(true, "*TEST[^ABCD]XXX", "lolTESTZXXX")]
        [DataRow(true, "*TEST[B-D]XXX", "lolTESTBXXX")]
        [DataRow(true, "*TEST[^B-D]XXX", "lolTESTZXXX")]
        [DataRow(true, "*Stuff.txt", "Stuff.txt")]
        [DataRow(false, "*Stuff.txt", "Stuff.TXT")]
        [DataRow(true, "*Stuff.txt", "MagicStuff.txt")]
        [DataRow(false, "*Stuff.txt", "MagicStuff.TXT")]
        [DataRow(false, "*Stuff.txt", "MagicStuff.txt.IMG")]
        [DataRow(false, "*Stuff.txt", "MagicStuff.TXT.IMG")]
        [DataRow(false, "*Stuff.txt", "Stuff.txt.IMG")]
        [DataRow(false, "*Stuff.txt", "Stuff.TXT.IMG")]
        [DataRow(false, "*Stuff.txt", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff.txt", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "Stuff.txt*", "Stuff.txt")]
        [DataRow(false, "Stuff.txt*", "Stuff.TXT")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.txt")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.TXT")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.txt.IMG")]
        [DataRow(false, "Stuff.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "Stuff.txt*", "Stuff.txt.IMG")]
        [DataRow(false, "Stuff.txt*", "Stuff.TXT.IMG")]
        [DataRow(false, "Stuff.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "Stuff.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff.txt*", "Stuff.txt")]
        [DataRow(false, "*Stuff.txt*", "Stuff.TXT")]
        [DataRow(true, "*Stuff.txt*", "MagicStuff.txt")]
        [DataRow(false, "*Stuff.txt*", "MagicStuff.TXT")]
        [DataRow(true, "*Stuff.txt*", "MagicStuff.txt.IMG")]
        [DataRow(false, "*Stuff.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "*Stuff.txt*", "Stuff.txt.IMG")]
        [DataRow(false, "*Stuff.txt*", "Stuff.TXT.IMG")]
        [DataRow(false, "*Stuff.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt", "Stuff.txt")]
        [DataRow(false, "*Stuff*.txt", "Stuff.TXT")]
        [DataRow(true, "*Stuff*.txt", "MagicStuff.txt")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff.TXT")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff.txt.IMG")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff.TXT.IMG")]
        [DataRow(false, "*Stuff*.txt", "Stuff.txt.IMG")]
        [DataRow(false, "*Stuff*.txt", "Stuff.TXT.IMG")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt", "MagicStuff001.txt")]
        [DataRow(false, "*Stuff*.txt", "MagicStuff001.TXT")]
        [DataRow(true, "Stuff*.txt*", "Stuff.txt")]
        [DataRow(false, "Stuff*.txt*", "Stuff.TXT")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.txt")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.TXT")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.txt.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "Stuff*.txt*", "Stuff.txt.IMG")]
        [DataRow(false, "Stuff*.txt*", "Stuff.TXT.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.txt")]
        [DataRow(false, "Stuff*.txt*", "MagicStuff001.TXT")]
        [DataRow(true, "*Stuff*.txt*", "Stuff.txt")]
        [DataRow(false, "*Stuff*.txt*", "Stuff.TXT")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff.txt")]
        [DataRow(false, "*Stuff*.txt*", "MagicStuff.TXT")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff.txt.IMG")]
        [DataRow(false, "*Stuff*.txt*", "MagicStuff.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt*", "Stuff.txt.IMG")]
        [DataRow(false, "*Stuff*.txt*", "Stuff.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff001.txt.IMG")]
        [DataRow(false, "*Stuff*.txt*", "MagicStuff001.TXT.IMG")]
        [DataRow(true, "*Stuff*.txt*", "MagicStuff001.txt")]
        [DataRow(false, "*Stuff*.txt*", "MagicStuff001.TXT")]
        [DataRow(true, "?Stuff?.txt?", "1Stuff3.txt4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff3.TXT4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff.txt4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff.TXT4")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff3.txt")]
        [DataRow(false, "?Stuff?.txt?", "1Stuff3.TXT")]
        [DataRow(false, "?Stuff?.txt?", "Stuff3.txt4")]
        [DataRow(false, "?Stuff?.txt?", "Stuff3.TXT4")]
        public void LikeTest_CaseSensitive(bool expected, string pattern, string text)
        {
            Assert.AreEqual(expected, text.Like(pattern, ignoreCase: false));
        }

        [TestMethod]
        [DataRow(true, "abcd_fg", "abcdefg")]
        [DataRow(true, "ab%f%", "abcdefg")]
        [DataRow(false, "abcd_fg", "abcdefghi")]
        [DataRow(true, "%", "")]
        [DataRow(true, "%", " ")]
        [DataRow(true, "%", "asdfa asdf asdf")]
        [DataRow(true, "%", "%")]
        [DataRow(false, "_", "")]
        [DataRow(true, "_", " ")]
        [DataRow(true, "_", "4")]
        [DataRow(true, "_", "C")]
        [DataRow(false, "_", "CX")]
        [DataRow(false, "[ABCD]", "")]
        [DataRow(true, "[ABCD]", "A")]
        [DataRow(true, "[ABCD]", "b")]
        [DataRow(false, "[ABCD]", "X")]
        [DataRow(false, "[ABCD]", "AB")]
        [DataRow(true, "[B-D]", "C")]
        [DataRow(true, "[B-D]", "D")]
        [DataRow(false, "[B-D]", "A")]
        [DataRow(false, "[^B-D]", "C")]
        [DataRow(false, "[^B-D]", "D")]
        [DataRow(true, "[^B-D]", "A")]
        [DataRow(true, "%TEST[ABCD]XXX", "lolTESTBXXX")]
        [DataRow(false, "%TEST[ABCD]XXX", "lolTESTZXXX")]
        [DataRow(false, "%TEST[^ABCD]XXX", "lolTESTBXXX")]
        [DataRow(true, "%TEST[^ABCD]XXX", "lolTESTZXXX")]
        [DataRow(true, "%TEST[B-D]XXX", "lolTESTBXXX")]
        [DataRow(true, "%TEST[^B-D]XXX", "lolTESTZXXX")]
        [DataRow(true, "%Stuff.txt", "Stuff.txt")]
        [DataRow(true, "%Stuff.txt", "MagicStuff.txt")]
        [DataRow(false, "%Stuff.txt", "MagicStuff.txt.IMG")]
        [DataRow(false, "%Stuff.txt", "Stuff.txt.IMG")]
        [DataRow(false, "%Stuff.txt", "MagicStuff001.txt.IMG")]
        [DataRow(true, "Stuff.txt%", "Stuff.txt")]
        [DataRow(false, "Stuff.txt%", "MagicStuff.txt")]
        [DataRow(false, "Stuff.txt%", "MagicStuff.txt.IMG")]
        [DataRow(true, "Stuff.txt%", "Stuff.txt.IMG")]
        [DataRow(false, "Stuff.txt%", "MagicStuff001.txt.IMG")]
        [DataRow(true, "%Stuff.txt%", "Stuff.txt")]
        [DataRow(true, "%Stuff.txt%", "MagicStuff.txt")]
        [DataRow(true, "%Stuff.txt%", "MagicStuff.txt.IMG")]
        [DataRow(true, "%Stuff.txt%", "Stuff.txt.IMG")]
        [DataRow(false, "%Stuff.txt%", "MagicStuff001.txt.IMG")]
        [DataRow(true, "%Stuff%.txt", "Stuff.txt")]
        [DataRow(true, "%Stuff%.txt", "MagicStuff.txt")]
        [DataRow(false, "%Stuff%.txt", "MagicStuff.txt.IMG")]
        [DataRow(false, "%Stuff%.txt", "Stuff.txt.IMG")]
        [DataRow(false, "%Stuff%.txt", "MagicStuff001.txt.IMG")]
        [DataRow(true, "%Stuff%.txt", "MagicStuff001.txt")]
        [DataRow(true, "Stuff%.txt%", "Stuff.txt")]
        [DataRow(false, "Stuff%.txt%", "MagicStuff.txt")]
        [DataRow(false, "Stuff%.txt%", "MagicStuff.txt.IMG")]
        [DataRow(true, "Stuff%.txt%", "Stuff.txt.IMG")]
        [DataRow(false, "Stuff%.txt%", "MagicStuff001.txt.IMG")]
        [DataRow(false, "Stuff%.txt%", "MagicStuff001.txt")]
        [DataRow(true, "%Stuff%.txt%", "Stuff.txt")]
        [DataRow(true, "%Stuff%.txt%", "MagicStuff.txt")]
        [DataRow(true, "%Stuff%.txt%", "MagicStuff.txt.IMG")]
        [DataRow(true, "%Stuff%.txt%", "Stuff.txt.IMG")]
        [DataRow(true, "%Stuff%.txt%", "MagicStuff001.txt.IMG")]
        [DataRow(true, "%Stuff%.txt%", "MagicStuff001.txt")]
        [DataRow(true, "_Stuff_.txt_", "1Stuff3.txt4")]
        [DataRow(false, "_Stuff_.txt_", "1Stuff.txt4")]
        [DataRow(false, "_Stuff_.txt_", "1Stuff3.txt")]
        [DataRow(false, "_Stuff_.txt_", "Stuff3.txt4")]
        public void LikeTest_SqlPattern(bool expected, string pattern, string text)
        {
            Assert.AreEqual(expected, text.Like(pattern,
                new StringLikeOptions { WildCard = '%', CharWildCard = '_' }));
        }

        [TestMethod]
        public void StringBuilder_Clear()
        {
            var builder = new System.Text.StringBuilder();

            builder.Append("Hola mundo.");
            Assert.AreEqual(11, builder.Length);
            Extensions.Clear(builder);
            Assert.AreEqual(0, builder.Length);
        }

    }
}
